export type Category =
  | "Dermatology"
  | "Cosmeceuticals"
  | "Trichology"
  | "General Medicine"
  | "Nutraceuticals"
  | "Gastroenterology";

export type Form =
  | "Gel"
  | "Serum"
  | "Capsule"
  | "Tablet"
  | "Hair Serum"
  | "Suspension"
  | "Cream"
  | "Lotion"
  | "Face Wash";

export interface Product {
  slug: string;
  name: string;
  generic: string;
  category: Category;
  form: Form;
  pack: string;
  rx: boolean;
  featured?: boolean;
  tagline: string;
  indications: string[];
  highlights: string[];
  moa: string;
  directions: string[];
  regulatory: string[];
  /** packshot palette */
  color: { from: string; to: string; text: string };
}

export const categories: Category[] = [
  "Dermatology",
  "Cosmeceuticals",
  "Trichology",
  "General Medicine",
  "Nutraceuticals",
  "Gastroenterology",
];

export const forms: Form[] = [
  "Gel",
  "Serum",
  "Hair Serum",
  "Cream",
  "Lotion",
  "Face Wash",
  "Capsule",
  "Tablet",
  "Suspension",
];

export const products: Product[] = [
  {
    slug: "avercin-gel",
    name: "Avercin Gel",
    generic: "Clindamycin Phosphate IP 1% w/w + Nicotinamide IP 4% w/w",
    category: "Dermatology",
    form: "Gel",
    pack: "20g Aluminium Laminated Tube",
    rx: true,
    featured: true,
    tagline: "Dual-action acne vulgaris management",
    indications: [
      "Acne vulgaris and inflammatory papules",
      "Comedones (blackheads & whiteheads)",
      "Redness and pustular acne lesions",
      "Post-acne hyperpigmentation",
    ],
    highlights: [
      "Dual antimicrobial + anti-inflammatory synergy",
      "Non-greasy, fast-absorbing hydro-gel base",
      "Clinically proven reduction in inflammatory acne lesions",
      "Well tolerated for long-term maintenance therapy",
    ],
    moa:
      "Clindamycin is a lincosamide antibiotic that inhibits bacterial protein synthesis by binding to the 50S ribosomal subunit, suppressing Cutibacterium acnes growth and reducing free fatty acid formation. Nicotinamide exerts a topical anti-inflammatory effect, reduces sebum production, and improves skin barrier function, complementing the antimicrobial action.",
    directions: [
      "Clean and dry the affected area before application",
      "Apply a thin film twice daily, or as directed by the physician",
      "Avoid contact with eyes, lips and mucous membranes",
      "Store below 25°C, protected from light; keep tube tightly closed",
      "Discontinue and consult physician if excessive dryness or irritation occurs",
    ],
    regulatory: [
      "Schedule H — Prescription Drug. To be sold on the prescription of a Registered Medical Practitioner only.",
      "Pack: 20g aluminium-barrier laminated tube in UV-varnished carton",
      "Batch-tested for content uniformity, pH, and microbial limits",
      "Shelf life: 24 months from date of manufacture",
    ],
    color: { from: "#0b5cab", to: "#16a34a", text: "#ffffff" },
  },
  {
    slug: "averiq-glow-serum",
    name: "Averiq Glow Serum",
    generic: "Vitamin C 15% + Ferulic Acid 0.5% + Hyaluronic Acid 1%",
    category: "Cosmeceuticals",
    form: "Serum",
    pack: "30ml Amber Dropper Bottle",
    rx: false,
    featured: true,
    tagline: "Brightening, firming, anti-aging antioxidant serum",
    indications: [
      "Skin brightening & dullness correction",
      "Hyperpigmentation and uneven tone",
      "Fine lines, wrinkles and photoaging",
      "Post-inflammatory erythema support",
    ],
    highlights: [
      "Stabilized 15% L-ascorbic acid for maximum efficacy",
      "Ferulic acid doubles antioxidant photoprotection",
      "Hyaluronic acid delivers deep, lasting hydration",
      "Fragrance-free, dermatologically tested formulation",
    ],
    moa:
      "L-Ascorbic acid neutralizes reactive oxygen species generated by UV exposure, inhibits tyrosinase for melanin suppression, and serves as a cofactor for collagen synthesis. Ferulic acid stabilizes vitamin C and amplifies its photoprotective capacity, while hyaluronic acid binds water in the dermis to plump and smooth skin.",
    directions: [
      "Apply 3–4 drops to cleansed face and neck every morning",
      "Follow with a broad-spectrum sunscreen (SPF 30+) during the day",
      "May cause mild tingling on first use; patch test recommended",
      "Store below 25°C, away from direct sunlight",
    ],
    regulatory: [
      "OTC cosmeceutical — for external use only",
      "Pack: 30ml amber glass dropper bottle with tamper-evident seal",
      "Nitrogen-flushed and oxygen-barrier packaging to preserve stability",
      "Shelf life: 18 months from date of manufacture",
    ],
    color: { from: "#f59e0b", to: "#0b5cab", text: "#ffffff" },
  },
  {
    slug: "averzole-it-200",
    name: "Averzole-IT 200",
    generic: "Itraconazole 200mg (Dual Coated Pellets)",
    category: "Dermatology",
    form: "Capsule",
    pack: "10x1x10 Alu-Alu Blister",
    rx: true,
    featured: true,
    tagline: "Broad-spectrum antifungal therapy",
    indications: [
      "Recurrent fungal infections",
      "Tinea cruris, tinea corporis & tinea pedis",
      "Pityriasis versicolor",
      "Onychomycosis and candidal infections",
    ],
    highlights: [
      "Dual-coated pellet technology for pH-independent absorption",
      "Consistent 200mg dose strength in a single capsule",
      "Superior bioavailability vs conventional capsules",
      "Convenient once-daily oral regimen",
    ],
    moa:
      "Itraconazole inhibits fungal cytochrome P-450 14α-demethylase, blocking the conversion of lanosterol to ergosterol. The resulting ergosterol depletion disrupts fungal cell membrane integrity and permeability, exerting a fungistatic effect against dermatophytes, yeasts and dimorphic fungi.",
    directions: [
      "Take capsules after a full meal for optimal absorption",
      "Swallow whole — do not crush or chew",
      "Duration of therapy as directed by the physician",
      "Inform physician about existing hepatic or cardiac conditions",
    ],
    regulatory: [
      "Schedule H — Prescription Drug. To be sold on the prescription of a Registered Medical Practitioner only.",
      "Pack: 10x1x10 Alu-Alu blister strips",
      "Bubble-packed dual-coated pellets for enhanced stability",
      "Shelf life: 24 months from date of manufacture",
    ],
    color: { from: "#0c4179", to: "#0b5cab", text: "#ffffff" },
  },
  {
    slug: "averfol-hair-serum",
    name: "Averfol Hair Serum",
    generic: "Procapil 3% + Redensyl 3% + Anagain 2% + Biotin",
    category: "Trichology",
    form: "Hair Serum",
    pack: "60ml Spray Bottle",
    rx: false,
    featured: true,
    tagline: "Science-backed hair regrowth & density",
    indications: [
      "Androgenetic alopecia (male & female pattern)",
      "Telogen effluvium and stress-related shedding",
      "Thinning hair and reduced hair density",
      "Postpartum hair fall",
    ],
    highlights: [
      "Triple-actives: Procapil, Redensyl & Anagain",
      "Clinically studied actives for visible density in 90 days",
      "Non-greasy, leave-on spray — no residue",
      "Suitable for daily use on all hair types",
    ],
    moa:
      "Redensyl stimulates dermal papilla cell proliferation and promotes the anagen (growth) phase of the hair cycle. Procapil combines matrikine peptides and apigenin to inhibit follicle fibrosis and DHT-related miniaturization, while Anagain reactivates dormant follicles and biotin supports keratin synthesis for stronger hair shafts.",
    directions: [
      "Spray 4–6 pumps directly onto dry scalp, focusing on thinning areas",
      "Massage gently for 1–2 minutes for absorption",
      "Use once daily, preferably at night; do not rinse",
      "Use consistently for a minimum of 90 days for best results",
    ],
    regulatory: [
      "OTC cosmeceutical — for external use only",
      "Pack: 60ml amber spray bottle with metered nozzle",
      "Dermatologically and trichologically tested",
      "Shelf life: 24 months from date of manufacture",
    ],
    color: { from: "#16a34a", to: "#062e5b", text: "#ffffff" },
  },
  {
    slug: "avermol-650",
    name: "Avermol-650",
    generic: "Paracetamol (Acetaminophen) IP 650mg",
    category: "General Medicine",
    form: "Tablet",
    pack: "10x10 Blister Pack",
    rx: false,
    featured: true,
    tagline: "Trusted antipyretic & analgesic",
    indications: [
      "Fever (pyrexia) including post-vaccine fever",
      "Mild to moderate pain — headache, bodyache",
      "Dental pain and musculoskeletal pain",
      "Fever and pain in common infections",
    ],
    highlights: [
      "Rapidly absorbed, gentle on the stomach",
      "Reliable antipyretic and analgesic action within 30–60 min",
      "Suitable for patients who cannot tolerate NSAIDs",
      "Available across all pack sizes for channel partners",
    ],
    moa:
      "Paracetamol inhibits prostaglandin synthesis in the central nervous system via cyclooxygenase (COX) inhibition and acts on the thermoregulatory center in the hypothalamus to reduce fever, while providing centrally mediated analgesia without significant anti-inflammatory or gastric ulcerogenic effects.",
    directions: [
      "Take 1 tablet every 4–6 hours as needed for fever or pain",
      "Do not exceed 4 tablets (2600mg) in 24 hours",
      "Avoid concurrent use with other paracetamol-containing products",
      "Not recommended in severe hepatic impairment",
    ],
    regulatory: [
      "OTC — non-prescription drug",
      "Pack: 10x10 clear PVC blister pack with printed carton",
      "White, film-coated, break-line tablets",
      "Shelf life: 36 months from date of manufacture",
    ],
    color: { from: "#64748b", to: "#0f172a", text: "#ffffff" },
  },
  {
    slug: "averpan-dsr",
    name: "Averpan-DSR",
    generic: "Pantoprazole Sodium 40mg + Domperidone 30mg SR",
    category: "Gastroenterology",
    form: "Capsule",
    pack: "10x10 Alu-Alu Blister",
    rx: true,
    tagline: "Complete acid reflux management",
    indications: [
      "Gastroesophageal reflux disease (GERD)",
      "Hyperacidity and heartburn",
      "Peptic and duodenal ulcers",
      "Functional dyspepsia with nausea",
    ],
    highlights: [
      "Dual-release: immediate domperidone + sustained pantoprazole",
      "Relieves both acidity and associated nausea",
      "Alu-Alu protection against moisture and degradation",
      "Once-daily dosing for patient compliance",
    ],
    moa:
      "Pantoprazole is a substituted benzimidazole proton-pump inhibitor that irreversibly inhibits the H+/K+-ATPase enzyme at the secretory surface of gastric parietal cells, suppressing basal and stimulated acid secretion. Domperidone, a peripheral dopamine D2 antagonist, enhances gastric motility and emptying, preventing reflux and controlling nausea.",
    directions: [
      "Take one capsule 30 minutes before breakfast, or as directed",
      "Swallow whole with water; do not crush or chew",
      "Maintenance therapy duration per physician guidance",
      "Inform physician about cardiac history (domperidone caution)",
    ],
    regulatory: [
      "Schedule H — Prescription Drug. To be sold on the prescription of a Registered Medical Practitioner only.",
      "Pack: 10x10 Alu-Alu blister strips",
      "Enteric-coated pantoprazole pellets + sustained-release domperidone",
      "Shelf life: 24 months from date of manufacture",
    ],
    color: { from: "#0b5cab", to: "#0a4e93", text: "#ffffff" },
  },
  {
    slug: "avercal-hd",
    name: "Avercal-HD",
    generic: "Calcium Carbonate 1250mg + Vitamin D3 2000 IU + Zinc 7.5mg",
    category: "Nutraceuticals",
    form: "Tablet",
    pack: "10x15 Blister Pack",
    rx: false,
    featured: true,
    tagline: "Bone density & immunity support",
    indications: [
      "Osteoporosis and osteopenia",
      "Calcium & vitamin D deficiency",
      "Bone density support in menopause",
      "Zinc supplementation for immunity",
    ],
    highlights: [
      "Elemental calcium 500mg per tablet",
      "High-dose Vitamin D3 2000 IU for absorption",
      "Zinc adds antioxidant and immune support",
      "Smooth, easy-to-swallow coated tablets",
    ],
    moa:
      "Calcium carbonate provides elemental calcium essential for bone mineralization and neuromuscular function. Vitamin D3 (cholecalciferol) enhances intestinal calcium and phosphate absorption and regulates bone remodeling via the VDR pathway. Zinc acts as a cofactor for over 300 enzymes, supporting immune function and collagen synthesis.",
    directions: [
      "Take one tablet daily after a meal, or as directed",
      "Best absorbed when taken with food containing fats",
      "Do not exceed the recommended daily dose",
      "Advise physician of concurrent medications (tetracyclines, thyroid)",
    ],
    regulatory: [
      "OTC nutraceutical dietary supplement — not a medicine",
      "Pack: 10x15 printed blister pack",
      "Contains no added sugar or artificial colors",
      "Shelf life: 24 months from date of manufacture",
    ],
    color: { from: "#16a34a", to: "#22c55e", text: "#ffffff" },
  },
  {
    slug: "averq-whitening-cream",
    name: "Averq Glutaglow Cream",
    generic: "Kojic Acid 2% + Alpha Arbutin 2% + Niacinamide 4%",
    category: "Cosmeceuticals",
    form: "Cream",
    pack: "30g Laminated Tube",
    rx: false,
    tagline: "Multi-target skin brightening",
    indications: [
      "Melasma and stubborn pigmentation",
      "Uneven skin tone and tanning",
      "Sun-induced dark spots",
      "Post-acne marks",
    ],
    highlights: [
      "Triple depigmenting actives on separate pathways",
      "Gentle, non-hydroquinone brightening formula",
      "Niacinamide soothes and strengthens the barrier",
      "Visible lightening in 4–8 weeks of consistent use",
    ],
    moa:
      "Kojic acid chelates copper at tyrosinase's active site, directly suppressing melanin synthesis. Alpha arbutin acts as a competitive tyrosinase inhibitor, while niacinamide blocks melanosome transfer from melanocytes to keratinocytes — attacking pigmentation at three independent stages.",
    directions: [
      "Apply a pea-sized amount to pigmented areas twice daily",
      "Use sunscreen (SPF 30+) every morning without fail",
      "Patch test behind the ear before first use",
      "Discontinue if excessive irritation develops",
    ],
    regulatory: [
      "OTC cosmeceutical — for external use only",
      "Pack: 30g aluminium tube in printed carton",
      "Paraben-reduced, dermatologically tested",
      "Shelf life: 24 months from date of manufacture",
    ],
    color: { from: "#d97706", to: "#b45309", text: "#ffffff" },
  },
  {
    slug: "averbiotic-200",
    name: "Averbiotic-200",
    generic: "Cefixime IP 200mg (Film-Coated Tablet)",
    category: "General Medicine",
    form: "Tablet",
    pack: "10x10 Alu-Alu Blister",
    rx: true,
    tagline: "Third-generation cephalosporin",
    indications: [
      "Upper & lower respiratory tract infections",
      "Urinary tract infections",
      "Otitis media and pharyngitis",
      "Uncomplicated gonococcal infections",
    ],
    highlights: [
      "Broad-spectrum third-generation cephalosporin",
      "Once or twice daily convenient dosing",
      "Stable film-coating for easy swallowing",
      "High batch-to-batch potency assurance",
    ],
    moa:
      "Cefixime is a third-generation cephalosporin that binds to penicillin-binding proteins (PBPs), inhibiting bacterial cell wall peptidoglycan synthesis. Its enhanced stability against β-lactamases extends activity to many resistant gram-negative and gram-positive organisms.",
    directions: [
      "Take as prescribed — usually 200–400mg daily in divided doses",
      "May be taken with or without food",
      "Complete the full course even if symptoms improve",
      "Report any allergic reaction immediately",
    ],
    regulatory: [
      "Schedule H — Prescription Drug. To be sold on the prescription of a Registered Medical Practitioner only.",
      "Pack: 10x10 Alu-Alu blister strips",
      "Film-coated, break-line tablets",
      "Shelf life: 24 months from date of manufacture",
    ],
    color: { from: "#0c4179", to: "#041d3a", text: "#ffffff" },
  },
  {
    slug: "averfol-shampoo",
    name: "Averfol Anti-Hairfall Shampoo",
    generic: "Keratin + Biotin + Procapil Complex",
    category: "Trichology",
    form: "Lotion",
    pack: "200ml Bottle",
    rx: false,
    tagline: "Clarifying, strengthening daily shampoo",
    indications: [
      "Hair fall control during wash",
      "Weak, brittle hair strands",
      "Scalp nourishment and root strengthening",
      "Post-treatment (serum) adjunct care",
    ],
    highlights: [
      "Sulfate-light, pH-balanced cleansing",
      "Keratin repairs the hair shaft cuticle",
      "Procapil supports follicle microcirculation",
      "Works synergistically with Averfol Hair Serum",
    ],
    moa:
      "Hydrolyzed keratin binds to damaged cuticle layers to smooth and reinforce the hair shaft, biotin and panthenol nourish the cortex, and Procapil improves scalp microcirculation and follicle anchoring — reducing wash-time shedding and improving strand resilience.",
    directions: [
      "Massage into wet scalp and hair, leave for 2 minutes",
      "Rinse thoroughly; use 3–4 times weekly",
      "Follow with conditioner if desired",
      "For external use only — avoid eye contact",
    ],
    regulatory: [
      "OTC cosmeceutical — for external use only",
      "Pack: 200ml HDPE bottle with flip cap",
      "Dermatologically tested",
      "Shelf life: 24 months from date of manufacture",
    ],
    color: { from: "#15803d", to: "#062e5b", text: "#ffffff" },
  },
  {
    slug: "averflam-plus",
    name: "Averflam-Plus",
    generic: "Diclofenac Sodium 50mg + Paracetamol 325mg + Serratiopeptidase 10mg",
    category: "General Medicine",
    form: "Tablet",
    pack: "10x10 Alu-Alu Blister",
    rx: true,
    tagline: "Rapid pain & inflammation relief",
    indications: [
      "Acute musculoskeletal pain",
      "Post-surgical inflammation and edema",
      "Dental and periodontal pain",
      "Rheumatic and soft-tissue pain",
    ],
    highlights: [
      "Triple-action: analgesic + antipyretic + anti-inflammatory",
      "Serratiopeptidase accelerates edema resolution",
      "Rapid onset of relief",
      "Well-documented safety profile",
    ],
    moa:
      "Diclofenac inhibits COX-1/COX-2 to reduce prostaglandin-mediated inflammation and pain. Paracetamol provides central analgesia, while serratiopeptidase, a proteolytic enzyme, breaks down fibrin and inflammatory mediators at the injury site, hastening resolution of swelling and tissue repair.",
    directions: [
      "Take one tablet after meals, 1–2 times daily or as directed",
      "Swallow whole with water",
      "Avoid in active peptic ulcer disease",
      "Caution in patients with cardiovascular or renal disease",
    ],
    regulatory: [
      "Schedule H — Prescription Drug. To be sold on the prescription of a Registered Medical Practitioner only.",
      "Pack: 10x10 Alu-Alu blister strips",
      "Enteric-coated diclofenac layer",
      "Shelf life: 24 months from date of manufacture",
    ],
    color: { from: "#b45309", to: "#7c2d12", text: "#ffffff" },
  },
  {
    slug: "avervit-multivitamin",
    name: "Avervit-MV",
    generic: "Multivitamin + Multimineral + L-Methylfolate",
    category: "Nutraceuticals",
    form: "Tablet",
    pack: "10x15 Blister Pack",
    rx: false,
    tagline: "Complete daily micronutrient coverage",
    indications: [
      "General nutritional deficiency",
      "Fatigue and low energy states",
      "Immunity support",
      "Antioxidant supplementation",
    ],
    highlights: [
      "22 micronutrients in bioavailable forms",
      "L-Methylfolate for direct folate utilization",
      "Iron-free option suitable for broader populations",
      "Once-daily dosing",
    ],
    moa:
      "Provides the full B-complex for energy metabolism (methylation via L-methylfolate and B12), antioxidant minerals (zinc, selenium, copper) for immune defense, and vitamin D3/K2 for bone and cardiovascular health — covering gaps in the modern Indian diet.",
    directions: [
      "Take one tablet daily after breakfast, or as directed",
      "Do not exceed recommended dosage",
      "Keep out of reach of children",
      "Inform physician of other supplements in use",
    ],
    regulatory: [
      "OTC nutraceutical dietary supplement — not a medicine",
      "Pack: 10x15 printed blister pack",
      "Contains no artificial preservatives",
      "Shelf life: 24 months from date of manufacture",
    ],
    color: { from: "#22c55e", to: "#16a34a", text: "#ffffff" },
  },
  {
    slug: "averq-fashwash",
    name: "Averq FashWash Face Wash",
    generic: "Salicylic Acid IP 2% w/w + Niacinamide IP 4% w/w",
    category: "Cosmeceuticals",
    form: "Face Wash",
    pack: "100g Squeeze Tube with Flip-Cap",
    rx: false,
    featured: true,
    tagline: "Deep-clean anti-acne daily face wash",
    indications: [
      "Oily and acne-prone skin",
      "Blackheads & whiteheads (comedones)",
      "Excess sebum and visible pores",
      "Dull, congested skin texture",
    ],
    highlights: [
      "2% salicylic acid (BHA) unclogs pores from within",
      "Niacinamide 4% controls oil and soothes redness",
      "Sulfate-light, pH 5.5 skin-friendly foaming base",
      "Gentle enough for twice-daily use",
    ],
    moa:
      "Salicylic acid is a lipophilic beta-hydroxy acid that penetrates sebum-filled pores, dissolves the intercellular cement holding dead skin cells, and exfoliates from within to clear comedones. Niacinamide reduces sebum production, calms inflammation, and strengthens the skin barrier, keeping pores clean longer after each wash.",
    directions: [
      "Wet face, massage a pea-sized amount for 30–60 seconds",
      "Pay extra attention to T-zone and acne-prone areas",
      "Rinse thoroughly with lukewarm water; use 1–2 times daily",
      "Avoid eye contact — rinse immediately with water if contact occurs",
    ],
    regulatory: [
      "OTC cosmeceutical — for external use only",
      "Pack: 100g squeeze tube with flip-cap, in printed carton",
      "Dermatologically tested, paraben-reduced formula",
      "Shelf life: 24 months from date of manufacture",
    ],
    color: { from: "#0d9488", to: "#065f46", text: "#ffffff" },
  },
  {
    slug: "averq-sunscreen-gel",
    name: "Averq Sunscreen Gel SPF 50+",
    generic: "Zinc Oxide 12% + Octinoxate 7.5% + Niacinamide 2% — SPF 50+ PA++++",
    category: "Cosmeceuticals",
    form: "Gel",
    pack: "50g Aluminium Tube",
    rx: false,
    featured: true,
    tagline: "Non-greasy broad-spectrum photoprotection",
    indications: [
      "Daily UVA & UVB protection (SPF 50+ PA++++)",
      "Prevention of photoaging and pigmentation",
      "Post-procedure / post-peel sun protection",
      "Tan prevention in outdoor exposure",
    ],
    highlights: [
      "Broad-spectrum SPF 50+ PA++++ dual-filter system",
      "Matte, non-greasy gel finish — suits Indian skin",
      "Niacinamide soothes and repairs post-sun skin",
      "Water-resistant up to 80 minutes",
    ],
    moa:
      "Zinc oxide physically reflects and scatters both UVA and UVB rays across the skin surface, while octinoxate absorbs UVB energy and converts it to harmless heat. Niacinamide adds antioxidant defense and accelerates barrier repair, reducing cumulative photodamage and pigment formation.",
    directions: [
      "Apply liberally 20 minutes before sun exposure",
      "Use a generous layer — about 2 finger-lengths for the face",
      "Reapply every 2–3 hours, and after swimming or sweating",
      "Use daily even on cloudy days or indoors near windows",
    ],
    regulatory: [
      "OTC cosmeceutical — for external use only",
      "Pack: 50g aluminium tube in printed carton",
      "Manufactured under WHO-GMP; complies with Indian cosmetic rules",
      "Shelf life: 24 months from date of manufacture",
    ],
    color: { from: "#f59e0b", to: "#ea580c", text: "#ffffff" },
  },
  {
    slug: "averq-acne-gel",
    name: "Averq Acne Control Gel",
    generic: "Adapalene IP 0.1% w/w + Clindamycin Phosphate IP 1% w/w",
    category: "Dermatology",
    form: "Gel",
    pack: "15g Aluminium Laminated Tube",
    rx: true,
    tagline: "Retinoid + antibiotic combination therapy",
    indications: [
      "Moderate acne vulgaris",
      "Comedonal and inflammatory acne lesions",
      "Acne with post-inflammatory pigmentation",
      "Maintenance of acne clearance",
    ],
    highlights: [
      "Once-daily nighttime retinoid gel",
      "Adapalene normalizes follicular keratinization",
      "Clindamycin suppresses C. acnes colonization",
      "Non-comedogenic, alcohol-free gel base",
    ],
    moa:
      "Adapalene binds nuclear retinoic acid receptors (RAR-β/γ) to normalize follicular epithelial desquamation, preventing microcomedone formation. Clindamycin inhibits bacterial protein synthesis at the 50S ribosomal subunit, reducing Cutibacterium acnes counts and the inflammatory cascade they trigger.",
    directions: [
      "Apply a thin layer to dry skin once daily at bedtime",
      "Start on alternate nights for the first two weeks to build tolerance",
      "Use moisturizer and SPF 50+ sunscreen every morning",
      "Avoid waxing, other retinoids and harsh scrubs during therapy",
    ],
    regulatory: [
      "Schedule H — Prescription Drug. To be sold on the prescription of a Registered Medical Practitioner only.",
      "Pack: 15g aluminium laminated tube in printed carton",
      "Photostable, air-tight barrier packaging",
      "Shelf life: 24 months from date of manufacture",
    ],
    color: { from: "#7c3aed", to: "#0b5cab", text: "#ffffff" },
  },
  {
    slug: "averiq-niacinamide-serum",
    name: "Averiq Niacinamide Serum",
    generic: "Niacinamide 10% + Zinc PCA 1% + Hyaluronic Acid",
    category: "Cosmeceuticals",
    form: "Serum",
    pack: "30ml Dropper Bottle",
    rx: false,
    tagline: "Oil control, pore refinement & barrier repair",
    indications: [
      "Oily and combination skin",
      "Enlarged pores and excess sebum",
      "Post-acne marks and uneven tone",
      "Dull, congested skin texture",
    ],
    highlights: [
      "10% niacinamide regulates sebum and refines pores",
      "Zinc PCA calms acne-prone, irritated skin",
      "Hyaluronic acid delivers lightweight hydration",
      "Fragrance-free, fast-absorbing watery texture",
    ],
    moa:
      "Niacinamide (vitamin B3) elevates cellular NAD+ levels, suppresses sebum synthesis, inhibits melanosome transfer and strengthens the lipid barrier. Zinc PCA exerts anti-inflammatory and mild antibacterial activity, while hyaluronic acid binds water to plump and soothe the skin surface.",
    directions: [
      "Apply 3–4 drops to cleansed face and neck, morning and night",
      "Follow with moisturizer; use sunscreen during the day",
      "May pair with retinol or vitamin C in separate routines",
      "Patch test before first use",
    ],
    regulatory: [
      "OTC cosmeceutical — for external use only",
      "Pack: 30ml amber glass dropper bottle, tamper-evident seal",
      "Dermatologically tested, fragrance-free",
      "Shelf life: 18 months from date of manufacture",
    ],
    color: { from: "#38bdf8", to: "#0b5cab", text: "#ffffff" },
  },
  {
    slug: "averiq-retinol-serum",
    name: "Averiq Retinol Night Serum",
    generic: "Retinol 0.5% + Bakuchiol 1% + Hyaluronic Acid 1%",
    category: "Cosmeceuticals",
    form: "Serum",
    pack: "30ml Amber Dropper Bottle",
    rx: false,
    featured: true,
    tagline: "Night renewal for fine lines & texture",
    indications: [
      "Fine lines and early wrinkles",
      "Uneven skin texture and roughness",
      "Photoaging and loss of firmness",
      "Post-acne scarring support",
    ],
    highlights: [
      "Stabilized 0.5% retinol in encapsulated slow-release form",
      "Bakuchiol — gentle plant-derived retinoid alternative",
      "Hyaluronic acid counteracts retinoid dryness",
      "Visible smoothness in 4–8 weeks of consistent use",
    ],
    moa:
      "Retinol is converted to retinoic acid in the skin, which binds retinoic acid receptors to accelerate epidermal turnover and stimulate collagen and elastin synthesis. Bakuchiol engages similar retinoid-like gene pathways with markedly less irritation, while hyaluronic acid sustains hydration during renewal.",
    directions: [
      "Use at night only — 2–3 drops on cleansed, dry skin",
      "Start 2–3 nights weekly, gradually increasing to nightly",
      "Always apply SPF 50+ sunscreen every morning",
      "Avoid combining with other strong actives initially",
    ],
    regulatory: [
      "OTC cosmeceutical — for external use only",
      "Pack: 30ml amber glass dropper bottle, oxygen-barrier closure",
      "Nitrogen-flushed packaging preserves retinol stability",
      "Shelf life: 18 months from date of manufacture",
    ],
    color: { from: "#e11d48", to: "#9d174d", text: "#ffffff" },
  },
  {
    slug: "averfol-max-hair-serum",
    name: "Averfol Max Hair Serum",
    generic: "Minoxidil IP 5% w/v + Redensyl 3% + Aminexil Complex",
    category: "Trichology",
    form: "Hair Serum",
    pack: "60ml Metered Spray Bottle",
    rx: true,
    tagline: "Maximum-strength clinically proven regrowth",
    indications: [
      "Androgenetic alopecia (male & female pattern)",
      "Hereditary thinning and receding hairline",
      "Early-stage pattern baldness",
      "Post-partum and stress-related shedding",
    ],
    highlights: [
      "5% minoxidil — the gold-standard regrowth active",
      "Redensyl reactivates dormant follicles",
      "Aminexil prevents collagen fibrosis around the follicle",
      "Metered 1ml spray dose per application",
    ],
    moa:
      "Minoxidil widens dermal papilla potassium channels, increases cutaneous blood flow and prolongs the anagen (growth) phase of the hair cycle. Redensyl stimulates dermal papilla cell proliferation, while aminexil inhibits lysyl hydroxylase to prevent perifollicular fibrosis that strangles the follicle.",
    directions: [
      "Apply 1ml (about 6 sprays) to dry scalp twice daily",
      "Massage gently for 1–2 minutes; wash hands after use",
      "Use consistently for a minimum of 4–6 months",
      "Avoid contact with eyes and broken skin",
    ],
    regulatory: [
      "Schedule H — Prescription Drug. To be sold on the prescription of a Registered Medical Practitioner only.",
      "Pack: 60ml metered spray bottle with calibrated nozzle",
      "Stabilized against oxidation; batch-tested for potency",
      "Shelf life: 24 months from date of manufacture",
    ],
    color: { from: "#065f46", to: "#0b5cab", text: "#ffffff" },
  },
  {
    slug: "averfol-tablets",
    name: "Averfol Hair Growth Tablets",
    generic: "Biotin 10mg + L-Cystine 75mg + Zinc 7.5mg + B-Complex & Amino Acids",
    category: "Nutraceuticals",
    form: "Tablet",
    pack: "10x10 Blister Pack",
    rx: false,
    featured: true,
    tagline: "Nutrition for stronger, fuller hair",
    indications: [
      "Nutritional hair thinning and shedding",
      "Weak, brittle and slow-growing hair",
      "Biotin and micronutrient deficiency",
      "Supportive therapy alongside topical hair serums",
    ],
    highlights: [
      "10mg biotin — the keratin-building vitamin",
      "L-cystine + methionine amino acid complex",
      "Zinc and B-complex nourish the follicle matrix",
      "Works synergistically with Averfol serums",
    ],
    moa:
      "Biotin acts as a coenzyme for carboxylases essential to keratin production, while L-cystine and methionine supply the sulfur amino acids that form keratin's disulfide bonds. Zinc supports follicle cell division and protein synthesis, and B-complex vitamins sustain the energy metabolism of rapidly dividing hair matrix cells.",
    directions: [
      "Take one tablet twice daily after meals, or as directed",
      "Continue for 3–6 months for visible improvement",
      "Do not exceed the recommended daily dose",
      "Keep out of reach of children",
    ],
    regulatory: [
      "OTC nutraceutical dietary supplement — not a medicine",
      "Pack: 10x10 printed blister pack",
      "Contains no added sugar or artificial colors",
      "Shelf life: 24 months from date of manufacture",
    ],
    color: { from: "#16a34a", to: "#15803d", text: "#ffffff" },
  },
];

export function getProduct(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function featuredProducts() {
  return products.filter((p) => p.featured);
}
